nginx:
    build: ./nginx
    links:
        - node1:node1
    ports:
        - '80:80'
    volumes:
        - ./data/certbot/conf:/etc/letsencrypt
        - ./data/certbot/www:/var/www/certbot
node1:
    build: ./node
    ports:
        - '8080'
    links:
        - redis
    environment:
        - 'TEST=some test env yeet'
redis:
    image: redis
    ports:
        - '6379'
certbot:
    image: certbot/certbot
    volumes:
        - ./data/certbot/conf:/etc/letsencrypt
        - ./data/certbot/www:/var/www/certbot
