nginx:
    build: ./nginx
    links:
        - node1:node1
    ports:
        - '80:80'
        - '443:443'
    volumes:
        - /etc/nginx/ssl/:/etc/nginx/ssl/
        - /var/log/nginx/:/var/log/nginx/
node1:
    build: ./node
    ports:
        - '8080'
    links:
        - redis
    volumes:
        - ./logs/:/app/logs/
redis:
    image: redis
    ports:
        - '6379'
