version: '3'

services:
    nginx:
        build: ./nginx
        links:
            - node:node
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - /etc/nginx/ssl/:/etc/nginx/ssl/
            - /var/log/nginx/:/var/log/nginx/
    node:
        build:
            context: ./node
            dockerfile: production.Dockerfile
        ports:
            - '8080'
        links:
            - redis
        volumes:
            - ./logs/:/app/logs/
        command: pm2-runtime start npm -- start
    redis:
        image: redis
        ports:
            - '6379'
